service: authorization-service
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev

functions:
  basicAuthorizer:
    handler: basicAuthorizer.basicAuthorizer
